### ISSUE TITLE
Data files meaning

### ISSUE THREAD

**Issue by thangld201** [mainlp/xsid#1]
Hi @robvanderg, I see in `data/xSID-0.5`, for each language X there are the `X.projectedTrain.conll`. `X.projectedTrain.conll.fixed`, `X.valid.conll`, `X.test.conll` files. I assume that the `valid` and `test` files were manually annotated, but how about the two `train` files ?

**Comment by robvanderg** [comment]
You are correct, valid and test are manually annotated, but the train files for all languages (except English) are automatically translated and annotated. You can read more about how it is done here: https://aclanthology.org/2021.naacl-main.197.pdf , and you can redo the translation for yourself using all python scripts that include "mt"  in the scripts folder. It should be noted that the span-labels for the slot detection are not very accurate (as you can see in the results in the paper).

**Comment by thangld201** [comment]
Thanks for clarifying. May I ask how `X.projectedTrain.conll` and `X.projectedTrain.conll.fixed` differ ?

**Comment by robvanderg** [comment]
That is done with: https://github.com/mainlp/xsid/blob/main/scripts/1.mt.predict.py , which calls https://github.com/mainlp/xsid/blob/main/scripts/fixBIO.py , it post-fixes the BIO labeling. So that "B-datetime I-loc" becomes "B-datetime I-datetime"
